// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEmbedding(ctx context.Context, arg CreateEmbeddingParams) (Embedding, error)
	DeleteEmbedding(ctx context.Context, chunkID pgtype.UUID) error
	GetEmbedding(ctx context.Context, chunkID pgtype.UUID) (Embedding, error)
	SearchChunksByProduct(ctx context.Context, arg SearchChunksByProductParams) ([]SearchChunksByProductRow, error)
	SearchChunksBySource(ctx context.Context, arg SearchChunksBySourceParams) ([]SearchChunksBySourceRow, error)
	SearchSimilarChunks(ctx context.Context, arg SearchSimilarChunksParams) ([]SearchSimilarChunksRow, error)
}

var _ Querier = (*Queries)(nil)
