// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chunks_extended.sql

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type CreateChunkBatchParams struct {
	FileID      pgtype.UUID `json:"file_id"`
	Ordinal     int32       `json:"ordinal"`
	StartLine   int32       `json:"start_line"`
	EndLine     int32       `json:"end_line"`
	Content     string      `json:"content"`
	ContentHash string      `json:"content_hash"`
	TokenCount  pgtype.Int4 `json:"token_count"`
}

type CreateEmbeddingBatchParams struct {
	ChunkID pgtype.UUID        `json:"chunk_id"`
	Vector  pgvector_go.Vector `json:"vector"`
	Model   string             `json:"model"`
}
