// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateChunkBatch implements pgx.CopyFromSource.
type iteratorForCreateChunkBatch struct {
	rows                 []CreateChunkBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateChunkBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateChunkBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].FileID,
		r.rows[0].Ordinal,
		r.rows[0].StartLine,
		r.rows[0].EndLine,
		r.rows[0].Content,
		r.rows[0].ContentHash,
		r.rows[0].TokenCount,
	}, nil
}

func (r iteratorForCreateChunkBatch) Err() error {
	return nil
}

func (q *Queries) CreateChunkBatch(ctx context.Context, arg []CreateChunkBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"chunks"}, []string{"file_id", "ordinal", "start_line", "end_line", "content", "content_hash", "token_count"}, &iteratorForCreateChunkBatch{rows: arg})
}

// iteratorForCreateEmbeddingBatch implements pgx.CopyFromSource.
type iteratorForCreateEmbeddingBatch struct {
	rows                 []CreateEmbeddingBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateEmbeddingBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateEmbeddingBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ChunkID,
		r.rows[0].Vector,
		r.rows[0].Model,
	}, nil
}

func (r iteratorForCreateEmbeddingBatch) Err() error {
	return nil
}

func (q *Queries) CreateEmbeddingBatch(ctx context.Context, arg []CreateEmbeddingBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"embeddings"}, []string{"chunk_id", "vector", "model"}, &iteratorForCreateEmbeddingBatch{rows: arg})
}
