// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: directory_summaries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const countDirectorySummariesBySnapshot = `-- name: CountDirectorySummariesBySnapshot :one
SELECT COUNT(*) FROM directory_summaries
WHERE snapshot_id = $1
`

func (q *Queries) CountDirectorySummariesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDirectorySummariesBySnapshot, snapshotID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDirectorySummary = `-- name: CreateDirectorySummary :one
INSERT INTO directory_summaries (
    snapshot_id,
    path,
    parent_path,
    depth,
    summary,
    embedding,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, snapshot_id, path, parent_path, depth, summary, embedding, metadata, created_at, updated_at
`

type CreateDirectorySummaryParams struct {
	SnapshotID pgtype.UUID        `json:"snapshot_id"`
	Path       string             `json:"path"`
	ParentPath pgtype.Text        `json:"parent_path"`
	Depth      int32              `json:"depth"`
	Summary    string             `json:"summary"`
	Embedding  pgvector_go.Vector `json:"embedding"`
	Metadata   []byte             `json:"metadata"`
}

func (q *Queries) CreateDirectorySummary(ctx context.Context, arg CreateDirectorySummaryParams) (DirectorySummary, error) {
	row := q.db.QueryRow(ctx, createDirectorySummary,
		arg.SnapshotID,
		arg.Path,
		arg.ParentPath,
		arg.Depth,
		arg.Summary,
		arg.Embedding,
		arg.Metadata,
	)
	var i DirectorySummary
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.Path,
		&i.ParentPath,
		&i.Depth,
		&i.Summary,
		&i.Embedding,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDirectorySummariesBySnapshot = `-- name: DeleteDirectorySummariesBySnapshot :exec
DELETE FROM directory_summaries
WHERE snapshot_id = $1
`

func (q *Queries) DeleteDirectorySummariesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDirectorySummariesBySnapshot, snapshotID)
	return err
}

const deleteDirectorySummaryByPath = `-- name: DeleteDirectorySummaryByPath :exec
DELETE FROM directory_summaries
WHERE snapshot_id = $1 AND path = $2
`

type DeleteDirectorySummaryByPathParams struct {
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	Path       string      `json:"path"`
}

func (q *Queries) DeleteDirectorySummaryByPath(ctx context.Context, arg DeleteDirectorySummaryByPathParams) error {
	_, err := q.db.Exec(ctx, deleteDirectorySummaryByPath, arg.SnapshotID, arg.Path)
	return err
}

const getDirectorySummaryByID = `-- name: GetDirectorySummaryByID :one
SELECT id, snapshot_id, path, parent_path, depth, summary, embedding, metadata, created_at, updated_at FROM directory_summaries
WHERE id = $1
`

func (q *Queries) GetDirectorySummaryByID(ctx context.Context, id pgtype.UUID) (DirectorySummary, error) {
	row := q.db.QueryRow(ctx, getDirectorySummaryByID, id)
	var i DirectorySummary
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.Path,
		&i.ParentPath,
		&i.Depth,
		&i.Summary,
		&i.Embedding,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDirectorySummaryByPath = `-- name: GetDirectorySummaryByPath :one
SELECT summary FROM directory_summaries
WHERE snapshot_id = $1 AND path = $2
`

type GetDirectorySummaryByPathParams struct {
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	Path       string      `json:"path"`
}

func (q *Queries) GetDirectorySummaryByPath(ctx context.Context, arg GetDirectorySummaryByPathParams) (string, error) {
	row := q.db.QueryRow(ctx, getDirectorySummaryByPath, arg.SnapshotID, arg.Path)
	var summary string
	err := row.Scan(&summary)
	return summary, err
}

const getMaxDepthBySnapshot = `-- name: GetMaxDepthBySnapshot :one
SELECT COALESCE(MAX(depth), 0) AS max_depth
FROM directory_summaries
WHERE snapshot_id = $1
`

func (q *Queries) GetMaxDepthBySnapshot(ctx context.Context, snapshotID pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getMaxDepthBySnapshot, snapshotID)
	var max_depth interface{}
	err := row.Scan(&max_depth)
	return max_depth, err
}

const listDirectorySummariesByDepth = `-- name: ListDirectorySummariesByDepth :many
SELECT id, snapshot_id, path, parent_path, depth, summary, embedding, metadata, created_at, updated_at FROM directory_summaries
WHERE snapshot_id = $1 AND depth = $2
ORDER BY path ASC
`

type ListDirectorySummariesByDepthParams struct {
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	Depth      int32       `json:"depth"`
}

func (q *Queries) ListDirectorySummariesByDepth(ctx context.Context, arg ListDirectorySummariesByDepthParams) ([]DirectorySummary, error) {
	rows, err := q.db.Query(ctx, listDirectorySummariesByDepth, arg.SnapshotID, arg.Depth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DirectorySummary{}
	for rows.Next() {
		var i DirectorySummary
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.Path,
			&i.ParentPath,
			&i.Depth,
			&i.Summary,
			&i.Embedding,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectorySummariesByParentPath = `-- name: ListDirectorySummariesByParentPath :many
SELECT id, snapshot_id, path, parent_path, depth, summary, embedding, metadata, created_at, updated_at FROM directory_summaries
WHERE snapshot_id = $1 AND parent_path = $2
ORDER BY path ASC
`

type ListDirectorySummariesByParentPathParams struct {
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	ParentPath pgtype.Text `json:"parent_path"`
}

func (q *Queries) ListDirectorySummariesByParentPath(ctx context.Context, arg ListDirectorySummariesByParentPathParams) ([]DirectorySummary, error) {
	rows, err := q.db.Query(ctx, listDirectorySummariesByParentPath, arg.SnapshotID, arg.ParentPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DirectorySummary{}
	for rows.Next() {
		var i DirectorySummary
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.Path,
			&i.ParentPath,
			&i.Depth,
			&i.Summary,
			&i.Embedding,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectorySummariesBySnapshot = `-- name: ListDirectorySummariesBySnapshot :many
SELECT id, snapshot_id, path, parent_path, depth, summary, embedding, metadata, created_at, updated_at FROM directory_summaries
WHERE snapshot_id = $1
ORDER BY depth ASC, path ASC
`

func (q *Queries) ListDirectorySummariesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) ([]DirectorySummary, error) {
	rows, err := q.db.Query(ctx, listDirectorySummariesBySnapshot, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DirectorySummary{}
	for rows.Next() {
		var i DirectorySummary
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.Path,
			&i.ParentPath,
			&i.Depth,
			&i.Summary,
			&i.Embedding,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDirectorySummariesByEmbedding = `-- name: SearchDirectorySummariesByEmbedding :many
SELECT
    id, snapshot_id, path, parent_path, depth, summary, embedding, metadata, created_at, updated_at,
    1 - (embedding <=> $1::vector) AS similarity
FROM directory_summaries
WHERE snapshot_id = $2
ORDER BY embedding <=> $1::vector
LIMIT $3
`

type SearchDirectorySummariesByEmbeddingParams struct {
	Column1    pgvector_go.Vector `json:"column_1"`
	SnapshotID pgtype.UUID        `json:"snapshot_id"`
	Limit      int32              `json:"limit"`
}

type SearchDirectorySummariesByEmbeddingRow struct {
	ID         pgtype.UUID        `json:"id"`
	SnapshotID pgtype.UUID        `json:"snapshot_id"`
	Path       string             `json:"path"`
	ParentPath pgtype.Text        `json:"parent_path"`
	Depth      int32              `json:"depth"`
	Summary    string             `json:"summary"`
	Embedding  pgvector_go.Vector `json:"embedding"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamp   `json:"created_at"`
	UpdatedAt  pgtype.Timestamp   `json:"updated_at"`
	Similarity int32              `json:"similarity"`
}

func (q *Queries) SearchDirectorySummariesByEmbedding(ctx context.Context, arg SearchDirectorySummariesByEmbeddingParams) ([]SearchDirectorySummariesByEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, searchDirectorySummariesByEmbedding, arg.Column1, arg.SnapshotID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDirectorySummariesByEmbeddingRow{}
	for rows.Next() {
		var i SearchDirectorySummariesByEmbeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.Path,
			&i.ParentPath,
			&i.Depth,
			&i.Summary,
			&i.Embedding,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDirectorySummary = `-- name: UpsertDirectorySummary :one
INSERT INTO directory_summaries (
    snapshot_id,
    path,
    parent_path,
    depth,
    summary,
    embedding,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (snapshot_id, path)
DO UPDATE SET
    parent_path = EXCLUDED.parent_path,
    depth = EXCLUDED.depth,
    summary = EXCLUDED.summary,
    embedding = EXCLUDED.embedding,
    metadata = EXCLUDED.metadata,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, snapshot_id, path, parent_path, depth, summary, embedding, metadata, created_at, updated_at
`

type UpsertDirectorySummaryParams struct {
	SnapshotID pgtype.UUID        `json:"snapshot_id"`
	Path       string             `json:"path"`
	ParentPath pgtype.Text        `json:"parent_path"`
	Depth      int32              `json:"depth"`
	Summary    string             `json:"summary"`
	Embedding  pgvector_go.Vector `json:"embedding"`
	Metadata   []byte             `json:"metadata"`
}

func (q *Queries) UpsertDirectorySummary(ctx context.Context, arg UpsertDirectorySummaryParams) (DirectorySummary, error) {
	row := q.db.QueryRow(ctx, upsertDirectorySummary,
		arg.SnapshotID,
		arg.Path,
		arg.ParentPath,
		arg.Depth,
		arg.Summary,
		arg.Embedding,
		arg.Metadata,
	)
	var i DirectorySummary
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.Path,
		&i.ParentPath,
		&i.Depth,
		&i.Summary,
		&i.Embedding,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
