// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: git_refs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGitRef = `-- name: CreateGitRef :one
INSERT INTO git_refs (source_id, ref_name, snapshot_id)
VALUES ($1, $2, $3)
ON CONFLICT (source_id, ref_name)
DO UPDATE SET snapshot_id = EXCLUDED.snapshot_id, updated_at = CURRENT_TIMESTAMP
RETURNING id, source_id, ref_name, snapshot_id, created_at, updated_at
`

type CreateGitRefParams struct {
	SourceID   pgtype.UUID `json:"source_id"`
	RefName    string      `json:"ref_name"`
	SnapshotID pgtype.UUID `json:"snapshot_id"`
}

func (q *Queries) CreateGitRef(ctx context.Context, arg CreateGitRefParams) (GitRef, error) {
	row := q.db.QueryRow(ctx, createGitRef, arg.SourceID, arg.RefName, arg.SnapshotID)
	var i GitRef
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.RefName,
		&i.SnapshotID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGitRef = `-- name: DeleteGitRef :exec
DELETE FROM git_refs
WHERE id = $1
`

func (q *Queries) DeleteGitRef(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGitRef, id)
	return err
}

const getGitRef = `-- name: GetGitRef :one
SELECT id, source_id, ref_name, snapshot_id, created_at, updated_at FROM git_refs
WHERE id = $1
`

func (q *Queries) GetGitRef(ctx context.Context, id pgtype.UUID) (GitRef, error) {
	row := q.db.QueryRow(ctx, getGitRef, id)
	var i GitRef
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.RefName,
		&i.SnapshotID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitRefByName = `-- name: GetGitRefByName :one
SELECT id, source_id, ref_name, snapshot_id, created_at, updated_at FROM git_refs
WHERE source_id = $1 AND ref_name = $2
`

type GetGitRefByNameParams struct {
	SourceID pgtype.UUID `json:"source_id"`
	RefName  string      `json:"ref_name"`
}

func (q *Queries) GetGitRefByName(ctx context.Context, arg GetGitRefByNameParams) (GitRef, error) {
	row := q.db.QueryRow(ctx, getGitRefByName, arg.SourceID, arg.RefName)
	var i GitRef
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.RefName,
		&i.SnapshotID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGitRefsBySource = `-- name: ListGitRefsBySource :many
SELECT id, source_id, ref_name, snapshot_id, created_at, updated_at FROM git_refs
WHERE source_id = $1
ORDER BY ref_name
`

func (q *Queries) ListGitRefsBySource(ctx context.Context, sourceID pgtype.UUID) ([]GitRef, error) {
	rows, err := q.db.Query(ctx, listGitRefsBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GitRef{}
	for rows.Next() {
		var i GitRef
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.RefName,
			&i.SnapshotID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGitRef = `-- name: UpdateGitRef :one
UPDATE git_refs
SET snapshot_id = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, source_id, ref_name, snapshot_id, created_at, updated_at
`

type UpdateGitRefParams struct {
	ID         pgtype.UUID `json:"id"`
	SnapshotID pgtype.UUID `json:"snapshot_id"`
}

func (q *Queries) UpdateGitRef(ctx context.Context, arg UpdateGitRefParams) (GitRef, error) {
	row := q.db.QueryRow(ctx, updateGitRef, arg.ID, arg.SnapshotID)
	var i GitRef
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.RefName,
		&i.SnapshotID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
