// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

// ファイルを分割したチャンク
type Chunk struct {
	// チャンクの一意識別子
	ID pgtype.UUID `json:"id"`
	// 所属するファイルのID
	FileID pgtype.UUID `json:"file_id"`
	// ファイル内でのチャンク序数（0始まり）
	Ordinal int32 `json:"ordinal"`
	// チャンクの開始行番号
	StartLine int32 `json:"start_line"`
	// チャンクの終了行番号
	EndLine int32 `json:"end_line"`
	// チャンクのテキスト内容
	Content string `json:"content"`
	// チャンク内容のSHA-256ハッシュ
	ContentHash string `json:"content_hash"`
	// 推定トークン数
	TokenCount pgtype.Int4      `json:"token_count"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

// チャンクのEmbeddingベクトル
type Embedding struct {
	// チャンクID（主キー兼外部キー）
	ChunkID pgtype.UUID `json:"chunk_id"`
	// Embeddingベクトル（1536次元）
	Vector pgvector_go.Vector `json:"vector"`
	// 使用したEmbeddingモデル名
	Model     string           `json:"model"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

// スナップショット内のファイル・ドキュメント情報
type File struct {
	// ファイルの一意識別子
	ID pgtype.UUID `json:"id"`
	// 所属するスナップショットのID
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	// ソースルートからの相対パス（またはドキュメント識別子）
	Path string `json:"path"`
	// ファイルサイズ（バイト）
	Size int64 `json:"size"`
	// MIMEタイプ形式のコンテンツ種別（例: text/x-go, text/x-python, text/markdown, application/pdf, text/html）
	ContentType string `json:"content_type"`
	// ファイル内容のSHA-256ハッシュ
	ContentHash string           `json:"content_hash"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

// Git専用の参照（ブランチ、タグ）管理
type GitRef struct {
	// Git参照の一意識別子
	ID pgtype.UUID `json:"id"`
	// 対象ソースのID（source_type=gitのみ）
	SourceID pgtype.UUID `json:"source_id"`
	// 参照名（ブランチ名またはタグ名: main, develop, v1.0.0 等）
	RefName string `json:"ref_name"`
	// 参照が指すスナップショットのID
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	// 参照の作成日時
	CreatedAt pgtype.Timestamp `json:"created_at"`
	// 参照の更新日時（別のコミットを指すようになった時）
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

// プロダクト（複数のソースをまとめる単位）
type Product struct {
	// プロダクトの一意識別子
	ID pgtype.UUID `json:"id"`
	// プロダクト名（一意）
	Name string `json:"name"`
	// プロダクトの説明
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

// ドキュメント・コードのソース情報（Git、Confluence、PDFなど）
type Source struct {
	// ソースの一意識別子
	ID pgtype.UUID `json:"id"`
	// 所属するプロダクトのID（必須）
	ProductID pgtype.UUID `json:"product_id"`
	// ソース名（一意）
	Name string `json:"name"`
	// ソースタイプ（git/confluence/pdf/redmine/notion/local）
	SourceType string `json:"source_type"`
	// ソースタイプ固有の情報（JSONBフォーマット）。例: Gitの場合 {"url": "git@github.com:...", "default_branch": "main"}、Confluenceの場合 {"base_url": "https://...", "space_key": "..."}
	Metadata  []byte           `json:"metadata"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

// ソースの特定バージョン時点のスナップショット
type SourceSnapshot struct {
	// スナップショットの一意識別子
	ID pgtype.UUID `json:"id"`
	// 対象ソースのID
	SourceID pgtype.UUID `json:"source_id"`
	// バージョン識別子（Gitの場合はcommit_hash、Confluenceの場合はpage_version、PDFの場合はfile_hash等）
	VersionIdentifier string `json:"version_identifier"`
	// インデックス完了フラグ
	Indexed bool `json:"indexed"`
	// インデックス完了日時
	IndexedAt pgtype.Timestamp `json:"indexed_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

// Wiki生成の実行履歴とメタデータ（プロダクト単位のみ）
type WikiMetadatum struct {
	// Wiki生成レコードの一意識別子
	ID pgtype.UUID `json:"id"`
	// 対象プロダクトのID
	ProductID pgtype.UUID `json:"product_id"`
	// Wikiファイルの出力先パス（例: /var/lib/dev-rag/wikis/my-ecommerce/）
	OutputPath string `json:"output_path"`
	// 生成されたWikiファイル数
	FileCount int32 `json:"file_count"`
	// Wiki生成完了日時
	GeneratedAt pgtype.Timestamp `json:"generated_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}
