// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateChunk(ctx context.Context, arg CreateChunkParams) (Chunk, error)
	CreateChunkBatch(ctx context.Context, arg []CreateChunkBatchParams) (int64, error)
	CreateEmbedding(ctx context.Context, arg CreateEmbeddingParams) (Embedding, error)
	CreateEmbeddingBatch(ctx context.Context, arg []CreateEmbeddingBatchParams) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateGitRef(ctx context.Context, arg CreateGitRefParams) (GitRef, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error)
	CreateSourceIfNotExists(ctx context.Context, arg CreateSourceIfNotExistsParams) (Source, error)
	CreateSourceSnapshot(ctx context.Context, arg CreateSourceSnapshotParams) (SourceSnapshot, error)
	CreateWikiMetadata(ctx context.Context, arg CreateWikiMetadataParams) (WikiMetadatum, error)
	DeleteChunk(ctx context.Context, id pgtype.UUID) error
	DeleteChunksByFile(ctx context.Context, fileID pgtype.UUID) error
	DeleteEmbedding(ctx context.Context, chunkID pgtype.UUID) error
	DeleteFile(ctx context.Context, id pgtype.UUID) error
	DeleteFilesByPaths(ctx context.Context, arg DeleteFilesByPathsParams) error
	DeleteFilesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) error
	DeleteGitRef(ctx context.Context, id pgtype.UUID) error
	DeleteProduct(ctx context.Context, id pgtype.UUID) error
	DeleteSource(ctx context.Context, id pgtype.UUID) error
	DeleteSourceSnapshot(ctx context.Context, id pgtype.UUID) error
	DeleteWikiMetadata(ctx context.Context, id pgtype.UUID) error
	FindChunksByContentHash(ctx context.Context, contentHash string) ([]Chunk, error)
	FindFilesByContentHash(ctx context.Context, contentHash string) ([]File, error)
	GetChunk(ctx context.Context, id pgtype.UUID) (Chunk, error)
	GetEmbedding(ctx context.Context, chunkID pgtype.UUID) (Embedding, error)
	GetFile(ctx context.Context, id pgtype.UUID) (File, error)
	GetFileByPath(ctx context.Context, arg GetFileByPathParams) (File, error)
	GetFileHashesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) ([]GetFileHashesBySnapshotRow, error)
	GetGitRef(ctx context.Context, id pgtype.UUID) (GitRef, error)
	GetGitRefByName(ctx context.Context, arg GetGitRefByNameParams) (GitRef, error)
	GetLatestIndexedSnapshot(ctx context.Context, sourceID pgtype.UUID) (SourceSnapshot, error)
	GetProduct(ctx context.Context, id pgtype.UUID) (Product, error)
	GetProductByName(ctx context.Context, name string) (Product, error)
	GetSource(ctx context.Context, id pgtype.UUID) (Source, error)
	GetSourceByName(ctx context.Context, name string) (Source, error)
	GetSourceSnapshot(ctx context.Context, id pgtype.UUID) (SourceSnapshot, error)
	GetSourceSnapshotByVersion(ctx context.Context, arg GetSourceSnapshotByVersionParams) (SourceSnapshot, error)
	GetWikiMetadata(ctx context.Context, id pgtype.UUID) (WikiMetadatum, error)
	GetWikiMetadataByProduct(ctx context.Context, productID pgtype.UUID) (WikiMetadatum, error)
	ListChunksByFile(ctx context.Context, fileID pgtype.UUID) ([]Chunk, error)
	ListChunksByOrdinalRange(ctx context.Context, arg ListChunksByOrdinalRangeParams) ([]Chunk, error)
	ListFilesByContentType(ctx context.Context, arg ListFilesByContentTypeParams) ([]File, error)
	ListFilesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) ([]File, error)
	ListGitRefsBySource(ctx context.Context, sourceID pgtype.UUID) ([]GitRef, error)
	ListIndexedSnapshots(ctx context.Context) ([]SourceSnapshot, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ListProductsWithStats(ctx context.Context) ([]ListProductsWithStatsRow, error)
	ListSourceSnapshotsBySource(ctx context.Context, sourceID pgtype.UUID) ([]SourceSnapshot, error)
	ListSourcesByProduct(ctx context.Context, productID pgtype.UUID) ([]Source, error)
	ListSourcesByType(ctx context.Context, sourceType string) ([]Source, error)
	ListWikiMetadata(ctx context.Context) ([]WikiMetadatum, error)
	MarkSnapshotIndexed(ctx context.Context, id pgtype.UUID) (SourceSnapshot, error)
	SearchChunksByProduct(ctx context.Context, arg SearchChunksByProductParams) ([]SearchChunksByProductRow, error)
	SearchChunksBySource(ctx context.Context, arg SearchChunksBySourceParams) ([]SearchChunksBySourceRow, error)
	SearchSimilarChunks(ctx context.Context, arg SearchSimilarChunksParams) ([]SearchSimilarChunksRow, error)
	UpdateGitRef(ctx context.Context, arg UpdateGitRefParams) (GitRef, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error)
}

var _ Querier = (*Queries)(nil)
