// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources_extended.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSourceIfNotExists = `-- name: CreateSourceIfNotExists :one
INSERT INTO sources (name, source_type, product_id, metadata)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name)
DO UPDATE SET
    source_type = EXCLUDED.source_type,
    product_id = EXCLUDED.product_id,
    metadata = EXCLUDED.metadata,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, product_id, name, source_type, metadata, created_at, updated_at
`

type CreateSourceIfNotExistsParams struct {
	Name       string      `json:"name"`
	SourceType string      `json:"source_type"`
	ProductID  pgtype.UUID `json:"product_id"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) CreateSourceIfNotExists(ctx context.Context, arg CreateSourceIfNotExistsParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSourceIfNotExists,
		arg.Name,
		arg.SourceType,
		arg.ProductID,
		arg.Metadata,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.SourceType,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
