// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSource = `-- name: CreateSource :one
INSERT INTO sources (product_id, name, source_type, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, name, source_type, metadata, created_at, updated_at
`

type CreateSourceParams struct {
	ProductID  pgtype.UUID `json:"product_id"`
	Name       string      `json:"name"`
	SourceType string      `json:"source_type"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.ProductID,
		arg.Name,
		arg.SourceType,
		arg.Metadata,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.SourceType,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources
WHERE id = $1
`

func (q *Queries) DeleteSource(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSource, id)
	return err
}

const getSource = `-- name: GetSource :one
SELECT id, product_id, name, source_type, metadata, created_at, updated_at FROM sources
WHERE id = $1
`

func (q *Queries) GetSource(ctx context.Context, id pgtype.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.SourceType,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSourceByName = `-- name: GetSourceByName :one
SELECT id, product_id, name, source_type, metadata, created_at, updated_at FROM sources
WHERE name = $1
`

func (q *Queries) GetSourceByName(ctx context.Context, name string) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByName, name)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.SourceType,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSourcesByProduct = `-- name: ListSourcesByProduct :many
SELECT id, product_id, name, source_type, metadata, created_at, updated_at FROM sources
WHERE product_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSourcesByProduct(ctx context.Context, productID pgtype.UUID) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.SourceType,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourcesByType = `-- name: ListSourcesByType :many
SELECT id, product_id, name, source_type, metadata, created_at, updated_at FROM sources
WHERE source_type = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSourcesByType(ctx context.Context, sourceType string) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesByType, sourceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.SourceType,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSource = `-- name: UpdateSource :one
UPDATE sources
SET name = $2, source_type = $3, metadata = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, product_id, name, source_type, metadata, created_at, updated_at
`

type UpdateSourceParams struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	SourceType string      `json:"source_type"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, updateSource,
		arg.ID,
		arg.Name,
		arg.SourceType,
		arg.Metadata,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.SourceType,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
