// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package sqlc

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const createEmbeddingBatch = `-- name: CreateEmbeddingBatch :batchexec
INSERT INTO embeddings (chunk_id, vector, model)
VALUES ($1, $2, $3)
`

type CreateEmbeddingBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateEmbeddingBatchParams struct {
	ChunkID pgtype.UUID        `json:"chunk_id"`
	Vector  pgvector_go.Vector `json:"vector"`
	Model   string             `json:"model"`
}

func (q *Queries) CreateEmbeddingBatch(ctx context.Context, arg []CreateEmbeddingBatchParams) *CreateEmbeddingBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ChunkID,
			a.Vector,
			a.Model,
		}
		batch.Queue(createEmbeddingBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateEmbeddingBatchBatchResults{br, len(arg), false}
}

func (b *CreateEmbeddingBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateEmbeddingBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
