// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (snapshot_id, path, size, content_type, content_hash, language, domain)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, snapshot_id, path, size, content_type, content_hash, language, domain, created_at
`

type CreateFileParams struct {
	SnapshotID  pgtype.UUID `json:"snapshot_id"`
	Path        string      `json:"path"`
	Size        int64       `json:"size"`
	ContentType string      `json:"content_type"`
	ContentHash string      `json:"content_hash"`
	Language    pgtype.Text `json:"language"`
	Domain      pgtype.Text `json:"domain"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.SnapshotID,
		arg.Path,
		arg.Size,
		arg.ContentType,
		arg.ContentHash,
		arg.Language,
		arg.Domain,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.Path,
		&i.Size,
		&i.ContentType,
		&i.ContentHash,
		&i.Language,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const deleteFilesByPaths = `-- name: DeleteFilesByPaths :exec
DELETE FROM files
WHERE snapshot_id = $1 AND path = ANY($2::text[])
`

type DeleteFilesByPathsParams struct {
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	Column2    []string    `json:"column_2"`
}

func (q *Queries) DeleteFilesByPaths(ctx context.Context, arg DeleteFilesByPathsParams) error {
	_, err := q.db.Exec(ctx, deleteFilesByPaths, arg.SnapshotID, arg.Column2)
	return err
}

const deleteFilesBySnapshot = `-- name: DeleteFilesBySnapshot :exec
DELETE FROM files
WHERE snapshot_id = $1
`

func (q *Queries) DeleteFilesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFilesBySnapshot, snapshotID)
	return err
}

const findFilesByContentHash = `-- name: FindFilesByContentHash :many
SELECT id, snapshot_id, path, size, content_type, content_hash, language, domain, created_at FROM files
WHERE content_hash = $1
ORDER BY created_at DESC
`

func (q *Queries) FindFilesByContentHash(ctx context.Context, contentHash string) ([]File, error) {
	rows, err := q.db.Query(ctx, findFilesByContentHash, contentHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.Path,
			&i.Size,
			&i.ContentType,
			&i.ContentHash,
			&i.Language,
			&i.Domain,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDomainCoverageBySnapshot = `-- name: GetDomainCoverageBySnapshot :many
SELECT
    COALESCE(f.domain, 'unknown') AS domain,
    COUNT(DISTINCT f.id) AS file_count,
    COALESCE(SUM(chunk_counts.chunk_count), 0) AS chunk_count
FROM files f
LEFT JOIN (
    SELECT file_id, COUNT(*) AS chunk_count
    FROM chunks
    GROUP BY file_id
) chunk_counts ON f.id = chunk_counts.file_id
WHERE f.snapshot_id = $1
GROUP BY f.domain
ORDER BY file_count DESC
`

type GetDomainCoverageBySnapshotRow struct {
	Domain     string      `json:"domain"`
	FileCount  int64       `json:"file_count"`
	ChunkCount interface{} `json:"chunk_count"`
}

// ドメイン別のファイル数とチャンク数を集計
func (q *Queries) GetDomainCoverageBySnapshot(ctx context.Context, snapshotID pgtype.UUID) ([]GetDomainCoverageBySnapshotRow, error) {
	rows, err := q.db.Query(ctx, getDomainCoverageBySnapshot, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDomainCoverageBySnapshotRow{}
	for rows.Next() {
		var i GetDomainCoverageBySnapshotRow
		if err := rows.Scan(&i.Domain, &i.FileCount, &i.ChunkCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFile = `-- name: GetFile :one
SELECT id, snapshot_id, path, size, content_type, content_hash, language, domain, created_at FROM files
WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id pgtype.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.Path,
		&i.Size,
		&i.ContentType,
		&i.ContentHash,
		&i.Language,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const getFileByPath = `-- name: GetFileByPath :one
SELECT id, snapshot_id, path, size, content_type, content_hash, language, domain, created_at FROM files
WHERE snapshot_id = $1 AND path = $2
`

type GetFileByPathParams struct {
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	Path       string      `json:"path"`
}

func (q *Queries) GetFileByPath(ctx context.Context, arg GetFileByPathParams) (File, error) {
	row := q.db.QueryRow(ctx, getFileByPath, arg.SnapshotID, arg.Path)
	var i File
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.Path,
		&i.Size,
		&i.ContentType,
		&i.ContentHash,
		&i.Language,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const getFileHashesBySnapshot = `-- name: GetFileHashesBySnapshot :many
SELECT path, content_hash
FROM files
WHERE snapshot_id = $1
`

type GetFileHashesBySnapshotRow struct {
	Path        string `json:"path"`
	ContentHash string `json:"content_hash"`
}

func (q *Queries) GetFileHashesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) ([]GetFileHashesBySnapshotRow, error) {
	rows, err := q.db.Query(ctx, getFileHashesBySnapshot, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFileHashesBySnapshotRow{}
	for rows.Next() {
		var i GetFileHashesBySnapshotRow
		if err := rows.Scan(&i.Path, &i.ContentHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByDomain = `-- name: GetFilesByDomain :many
SELECT id, snapshot_id, path, size, content_type, content_hash, language, domain, created_at FROM files
WHERE snapshot_id = $1 AND domain = $2
ORDER BY path
`

type GetFilesByDomainParams struct {
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	Domain     pgtype.Text `json:"domain"`
}

// 指定したドメインのファイル一覧を取得
func (q *Queries) GetFilesByDomain(ctx context.Context, arg GetFilesByDomainParams) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesByDomain, arg.SnapshotID, arg.Domain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.Path,
			&i.Size,
			&i.ContentType,
			&i.ContentHash,
			&i.Language,
			&i.Domain,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByContentType = `-- name: ListFilesByContentType :many
SELECT id, snapshot_id, path, size, content_type, content_hash, language, domain, created_at FROM files
WHERE snapshot_id = $1 AND content_type = $2
ORDER BY path
`

type ListFilesByContentTypeParams struct {
	SnapshotID  pgtype.UUID `json:"snapshot_id"`
	ContentType string      `json:"content_type"`
}

func (q *Queries) ListFilesByContentType(ctx context.Context, arg ListFilesByContentTypeParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByContentType, arg.SnapshotID, arg.ContentType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.Path,
			&i.Size,
			&i.ContentType,
			&i.ContentHash,
			&i.Language,
			&i.Domain,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesBySnapshot = `-- name: ListFilesBySnapshot :many
SELECT id, snapshot_id, path, size, content_type, content_hash, language, domain, created_at FROM files
WHERE snapshot_id = $1
ORDER BY path
`

func (q *Queries) ListFilesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesBySnapshot, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.Path,
			&i.Size,
			&i.ContentType,
			&i.ContentHash,
			&i.Language,
			&i.Domain,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
