// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: summaries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSummariesByType = `-- name: CountSummariesByType :one
SELECT COUNT(*) FROM summaries
WHERE snapshot_id = $1 AND summary_type = $2
`

type CountSummariesByTypeParams struct {
	SnapshotID  pgtype.UUID `json:"snapshot_id"`
	SummaryType string      `json:"summary_type"`
}

func (q *Queries) CountSummariesByType(ctx context.Context, arg CountSummariesByTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSummariesByType, arg.SnapshotID, arg.SummaryType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSummary = `-- name: CreateSummary :one
INSERT INTO summaries (snapshot_id, summary_type, target_path, depth, parent_path, arch_type, content, content_hash, source_hash, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, snapshot_id, summary_type, target_path, depth, parent_path, arch_type, content, content_hash, source_hash, metadata, created_at, updated_at
`

type CreateSummaryParams struct {
	SnapshotID  pgtype.UUID `json:"snapshot_id"`
	SummaryType string      `json:"summary_type"`
	TargetPath  string      `json:"target_path"`
	Depth       pgtype.Int4 `json:"depth"`
	ParentPath  pgtype.Text `json:"parent_path"`
	ArchType    pgtype.Text `json:"arch_type"`
	Content     string      `json:"content"`
	ContentHash string      `json:"content_hash"`
	SourceHash  string      `json:"source_hash"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateSummary(ctx context.Context, arg CreateSummaryParams) (Summary, error) {
	row := q.db.QueryRow(ctx, createSummary,
		arg.SnapshotID,
		arg.SummaryType,
		arg.TargetPath,
		arg.Depth,
		arg.ParentPath,
		arg.ArchType,
		arg.Content,
		arg.ContentHash,
		arg.SourceHash,
		arg.Metadata,
	)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.SummaryType,
		&i.TargetPath,
		&i.Depth,
		&i.ParentPath,
		&i.ArchType,
		&i.Content,
		&i.ContentHash,
		&i.SourceHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSummariesBySnapshot = `-- name: DeleteSummariesBySnapshot :exec
DELETE FROM summaries WHERE snapshot_id = $1
`

func (q *Queries) DeleteSummariesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSummariesBySnapshot, snapshotID)
	return err
}

const deleteSummary = `-- name: DeleteSummary :exec
DELETE FROM summaries WHERE id = $1
`

func (q *Queries) DeleteSummary(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSummary, id)
	return err
}

const getArchitectureSummary = `-- name: GetArchitectureSummary :one
SELECT id, snapshot_id, summary_type, target_path, depth, parent_path, arch_type, content, content_hash, source_hash, metadata, created_at, updated_at FROM summaries
WHERE snapshot_id = $1 AND summary_type = 'architecture' AND arch_type = $2
`

type GetArchitectureSummaryParams struct {
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	ArchType   pgtype.Text `json:"arch_type"`
}

func (q *Queries) GetArchitectureSummary(ctx context.Context, arg GetArchitectureSummaryParams) (Summary, error) {
	row := q.db.QueryRow(ctx, getArchitectureSummary, arg.SnapshotID, arg.ArchType)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.SummaryType,
		&i.TargetPath,
		&i.Depth,
		&i.ParentPath,
		&i.ArchType,
		&i.Content,
		&i.ContentHash,
		&i.SourceHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDirectorySummary = `-- name: GetDirectorySummary :one
SELECT id, snapshot_id, summary_type, target_path, depth, parent_path, arch_type, content, content_hash, source_hash, metadata, created_at, updated_at FROM summaries
WHERE snapshot_id = $1 AND summary_type = 'directory' AND target_path = $2
`

type GetDirectorySummaryParams struct {
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	TargetPath string      `json:"target_path"`
}

func (q *Queries) GetDirectorySummary(ctx context.Context, arg GetDirectorySummaryParams) (Summary, error) {
	row := q.db.QueryRow(ctx, getDirectorySummary, arg.SnapshotID, arg.TargetPath)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.SummaryType,
		&i.TargetPath,
		&i.Depth,
		&i.ParentPath,
		&i.ArchType,
		&i.Content,
		&i.ContentHash,
		&i.SourceHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileSummary = `-- name: GetFileSummary :one
SELECT id, snapshot_id, summary_type, target_path, depth, parent_path, arch_type, content, content_hash, source_hash, metadata, created_at, updated_at FROM summaries
WHERE snapshot_id = $1 AND summary_type = 'file' AND target_path = $2
`

type GetFileSummaryParams struct {
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	TargetPath string      `json:"target_path"`
}

func (q *Queries) GetFileSummary(ctx context.Context, arg GetFileSummaryParams) (Summary, error) {
	row := q.db.QueryRow(ctx, getFileSummary, arg.SnapshotID, arg.TargetPath)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.SummaryType,
		&i.TargetPath,
		&i.Depth,
		&i.ParentPath,
		&i.ArchType,
		&i.Content,
		&i.ContentHash,
		&i.SourceHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaxDirectoryDepth = `-- name: GetMaxDirectoryDepth :one
SELECT COALESCE(MAX(depth), 0)::int FROM summaries
WHERE snapshot_id = $1 AND summary_type = 'directory'
`

func (q *Queries) GetMaxDirectoryDepth(ctx context.Context, snapshotID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxDirectoryDepth, snapshotID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getSummaryByID = `-- name: GetSummaryByID :one
SELECT id, snapshot_id, summary_type, target_path, depth, parent_path, arch_type, content, content_hash, source_hash, metadata, created_at, updated_at FROM summaries WHERE id = $1
`

func (q *Queries) GetSummaryByID(ctx context.Context, id pgtype.UUID) (Summary, error) {
	row := q.db.QueryRow(ctx, getSummaryByID, id)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.SummaryType,
		&i.TargetPath,
		&i.Depth,
		&i.ParentPath,
		&i.ArchType,
		&i.Content,
		&i.ContentHash,
		&i.SourceHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArchitectureSummariesBySnapshot = `-- name: ListArchitectureSummariesBySnapshot :many
SELECT id, snapshot_id, summary_type, target_path, depth, parent_path, arch_type, content, content_hash, source_hash, metadata, created_at, updated_at FROM summaries
WHERE snapshot_id = $1 AND summary_type = 'architecture'
`

func (q *Queries) ListArchitectureSummariesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) ([]Summary, error) {
	rows, err := q.db.Query(ctx, listArchitectureSummariesBySnapshot, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Summary{}
	for rows.Next() {
		var i Summary
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.SummaryType,
			&i.TargetPath,
			&i.Depth,
			&i.ParentPath,
			&i.ArchType,
			&i.Content,
			&i.ContentHash,
			&i.SourceHash,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectorySummariesByDepth = `-- name: ListDirectorySummariesByDepth :many
SELECT id, snapshot_id, summary_type, target_path, depth, parent_path, arch_type, content, content_hash, source_hash, metadata, created_at, updated_at FROM summaries
WHERE snapshot_id = $1 AND summary_type = 'directory' AND depth = $2
ORDER BY target_path
`

type ListDirectorySummariesByDepthParams struct {
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	Depth      pgtype.Int4 `json:"depth"`
}

func (q *Queries) ListDirectorySummariesByDepth(ctx context.Context, arg ListDirectorySummariesByDepthParams) ([]Summary, error) {
	rows, err := q.db.Query(ctx, listDirectorySummariesByDepth, arg.SnapshotID, arg.Depth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Summary{}
	for rows.Next() {
		var i Summary
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.SummaryType,
			&i.TargetPath,
			&i.Depth,
			&i.ParentPath,
			&i.ArchType,
			&i.Content,
			&i.ContentHash,
			&i.SourceHash,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectorySummariesBySnapshot = `-- name: ListDirectorySummariesBySnapshot :many
SELECT id, snapshot_id, summary_type, target_path, depth, parent_path, arch_type, content, content_hash, source_hash, metadata, created_at, updated_at FROM summaries
WHERE snapshot_id = $1 AND summary_type = 'directory'
ORDER BY depth DESC, target_path
`

func (q *Queries) ListDirectorySummariesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) ([]Summary, error) {
	rows, err := q.db.Query(ctx, listDirectorySummariesBySnapshot, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Summary{}
	for rows.Next() {
		var i Summary
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.SummaryType,
			&i.TargetPath,
			&i.Depth,
			&i.ParentPath,
			&i.ArchType,
			&i.Content,
			&i.ContentHash,
			&i.SourceHash,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileSummariesBySnapshot = `-- name: ListFileSummariesBySnapshot :many
SELECT id, snapshot_id, summary_type, target_path, depth, parent_path, arch_type, content, content_hash, source_hash, metadata, created_at, updated_at FROM summaries
WHERE snapshot_id = $1 AND summary_type = 'file'
ORDER BY target_path
`

func (q *Queries) ListFileSummariesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) ([]Summary, error) {
	rows, err := q.db.Query(ctx, listFileSummariesBySnapshot, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Summary{}
	for rows.Next() {
		var i Summary
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.SummaryType,
			&i.TargetPath,
			&i.Depth,
			&i.ParentPath,
			&i.ArchType,
			&i.Content,
			&i.ContentHash,
			&i.SourceHash,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSummariesByType = `-- name: ListSummariesByType :many
SELECT id, snapshot_id, summary_type, target_path, depth, parent_path, arch_type, content, content_hash, source_hash, metadata, created_at, updated_at FROM summaries
WHERE snapshot_id = $1 AND summary_type = $2
ORDER BY created_at DESC
`

type ListSummariesByTypeParams struct {
	SnapshotID  pgtype.UUID `json:"snapshot_id"`
	SummaryType string      `json:"summary_type"`
}

func (q *Queries) ListSummariesByType(ctx context.Context, arg ListSummariesByTypeParams) ([]Summary, error) {
	rows, err := q.db.Query(ctx, listSummariesByType, arg.SnapshotID, arg.SummaryType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Summary{}
	for rows.Next() {
		var i Summary
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.SummaryType,
			&i.TargetPath,
			&i.Depth,
			&i.ParentPath,
			&i.ArchType,
			&i.Content,
			&i.ContentHash,
			&i.SourceHash,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSummary = `-- name: UpdateSummary :one
UPDATE summaries
SET content = $2, content_hash = $3, source_hash = $4, metadata = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, snapshot_id, summary_type, target_path, depth, parent_path, arch_type, content, content_hash, source_hash, metadata, created_at, updated_at
`

type UpdateSummaryParams struct {
	ID          pgtype.UUID `json:"id"`
	Content     string      `json:"content"`
	ContentHash string      `json:"content_hash"`
	SourceHash  string      `json:"source_hash"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) UpdateSummary(ctx context.Context, arg UpdateSummaryParams) (Summary, error) {
	row := q.db.QueryRow(ctx, updateSummary,
		arg.ID,
		arg.Content,
		arg.ContentHash,
		arg.SourceHash,
		arg.Metadata,
	)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.SummaryType,
		&i.TargetPath,
		&i.Depth,
		&i.ParentPath,
		&i.ArchType,
		&i.Content,
		&i.ContentHash,
		&i.SourceHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
