// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

// 品質改善アクションのバックログを管理するテーブル
type ActionBacklog struct {
	// アクションの一意識別子（UUID）
	ID pgtype.UUID `json:"id"`
	// ビジネス識別子（例: ACT-2025-001）
	ActionID string `json:"action_id"`
	// アクション生成に使用されたプロンプトバージョン
	PromptVersion string `json:"prompt_version"`
	// 優先度（P1: 最高, P2: 中, P3: 低）
	Priority string `json:"priority"`
	// アクション種別（reindex: 再インデックス, doc_fix: ドキュメント修正, test_update: テスト更新, investigate: 調査）
	ActionType string `json:"action_type"`
	// アクションのタイトル
	Title string `json:"title"`
	// アクションの詳細説明
	Description string `json:"description"`
	// 関連ファイルパスのJSONBリスト
	LinkedFiles []byte `json:"linked_files"`
	// 担当者のヒント（CODEOWNERSやレビュー者から推定）
	OwnerHint pgtype.Text `json:"owner_hint"`
	// 受け入れ基準（機械的に検証可能な条件）
	AcceptanceCriteria string `json:"acceptance_criteria"`
	// ステータス（open: 未完了, noop: 実行不要, completed: 完了）
	Status string `json:"status"`
	// アクションの作成日時
	CreatedAt pgtype.Timestamp `json:"created_at"`
	// アクションの完了日時（完了済みの場合のみ）
	CompletedAt pgtype.Timestamp `json:"completed_at"`
}

// システム全体のアーキテクチャ要約（LLMが生成）
type ArchitectureSummary struct {
	// 要約の一意識別子
	ID pgtype.UUID `json:"id"`
	// 対象スナップショットのID
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	// 要約種別（overview/tech_stack/data_flow/components）
	SummaryType string `json:"summary_type"`
	// LLMが生成した要約（Markdown形式）
	Summary string `json:"summary"`
	// Embeddingベクトル（pgvectorの制約により列全体で次元固定、最初のINSERT時の次元で確定）
	Embedding pgvector_go.Vector `json:"embedding"`
	// メタデータ（統計情報、次元数等。metadata.dimに実際の次元数を記録）
	Metadata  []byte           `json:"metadata"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

// ファイルを分割したチャンク
type Chunk struct {
	// チャンクの一意識別子
	ID pgtype.UUID `json:"id"`
	// 所属するファイルのID
	FileID pgtype.UUID `json:"file_id"`
	// ファイル内でのチャンク序数（0始まり）
	Ordinal int32 `json:"ordinal"`
	// チャンクの開始行番号
	StartLine int32 `json:"start_line"`
	// チャンクの終了行番号
	EndLine int32 `json:"end_line"`
	// チャンクのテキスト内容
	Content string `json:"content"`
	// チャンク内容のSHA-256ハッシュ
	ContentHash string `json:"content_hash"`
	// 推定トークン数
	TokenCount pgtype.Int4 `json:"token_count"`
	// チャンクの種類（function, method, struct, interface, const, var等）
	ChunkType pgtype.Text `json:"chunk_type"`
	// 関数名、クラス名、メソッド名等
	ChunkName pgtype.Text `json:"chunk_name"`
	// 所属する構造体名、パッケージ名等
	ParentName pgtype.Text `json:"parent_name"`
	// 関数シグネチャ（引数、戻り値）
	Signature pgtype.Text `json:"signature"`
	// ドキュメントコメント（GoDocコメント等）
	DocComment pgtype.Text `json:"doc_comment"`
	// インポートされているパッケージリスト（JSON配列）
	Imports []byte `json:"imports"`
	// 呼び出されている関数リスト（JSON配列）
	Calls []byte `json:"calls"`
	// コード行数（コメント・空行を除く）
	LinesOfCode pgtype.Int4 `json:"lines_of_code"`
	// コメント比率（0.00〜1.00）
	CommentRatio pgtype.Numeric `json:"comment_ratio"`
	// 循環的複雑度（McCabe複雑度）
	CyclomaticComplexity pgtype.Int4 `json:"cyclomatic_complexity"`
	// Embedding生成用の拡張コンテキスト
	EmbeddingContext pgtype.Text `json:"embedding_context"`
	// 階層レベル（1:ファイルサマリー, 2:関数/クラス, 3:ロジック単位）
	Level int32 `json:"level"`
	// 重要度スコア（0.0000〜1.0000、参照回数・中心性・編集頻度から算出）
	ImportanceScore  pgtype.Numeric `json:"importance_score"`
	StandardImports  []byte         `json:"standard_imports"`
	ExternalImports  []byte         `json:"external_imports"`
	InternalCalls    []byte         `json:"internal_calls"`
	ExternalCalls    []byte         `json:"external_calls"`
	TypeDependencies []byte         `json:"type_dependencies"`
	// 所属するスナップショットID（トレーサビリティ用）
	SourceSnapshotID pgtype.UUID `json:"source_snapshot_id"`
	// Gitコミットハッシュ（トレーサビリティ用）
	GitCommitHash pgtype.Text `json:"git_commit_hash"`
	// 最終更新者（Git author）
	Author pgtype.Text `json:"author"`
	// ファイル最終更新日時（コミット日時）
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	// インデックス作成日時
	IndexedAt pgtype.Timestamp `json:"indexed_at"`
	// ファイルバージョン識別子（オプション）
	FileVersion pgtype.Text `json:"file_version"`
	// 最新バージョンフラグ（true=最新、false=過去バージョン）
	IsLatest bool `json:"is_latest"`
	// 決定的な識別子（{product_name}/{source_name}/{file_path}#L{start}-L{end}@{commit_hash}）
	ChunkKey  string           `json:"chunk_key"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

// チャンク間の依存関係を管理するテーブル
type ChunkDependency struct {
	ID pgtype.UUID `json:"id"`
	// 依存元のチャンクID
	FromChunkID pgtype.UUID `json:"from_chunk_id"`
	// 依存先のチャンクID
	ToChunkID pgtype.UUID `json:"to_chunk_id"`
	// 依存関係の種類（call: 関数呼び出し、import: インポート、type: 型依存）
	DepType string `json:"dep_type"`
	// 依存の対象シンボル名
	Symbol    pgtype.Text      `json:"symbol"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

// チャンクの親子関係を管理する中間テーブル（階層構造の単一の真実源）
type ChunkHierarchy struct {
	// 親チャンクのID
	ParentChunkID pgtype.UUID `json:"parent_chunk_id"`
	// 子チャンクのID
	ChildChunkID pgtype.UUID `json:"child_chunk_id"`
	// 同一親配下での子チャンクの順序（0始まり）
	Ordinal int32 `json:"ordinal"`
	// 関係の作成日時
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

// ディレクトリごとの要約（LLMが生成）
type DirectorySummary struct {
	// 要約の一意識別子
	ID pgtype.UUID `json:"id"`
	// 対象スナップショットのID
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	// ディレクトリパス
	Path string `json:"path"`
	// 親ディレクトリパス（階層構造用）
	ParentPath pgtype.Text `json:"parent_path"`
	// ディレクトリの深さ（0=ルート）
	Depth int32 `json:"depth"`
	// LLMが生成した要約（Markdown形式）
	Summary string `json:"summary"`
	// Embeddingベクトル（pgvectorの制約により列全体で次元固定、最初のINSERT時の次元で確定）
	Embedding pgvector_go.Vector `json:"embedding"`
	// メタデータ（ファイル数、言語統計、次元数等。metadata.dimに実際の次元数を記録）
	Metadata  []byte           `json:"metadata"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

// チャンクのEmbeddingベクトル
type Embedding struct {
	// チャンクID（主キー兼外部キー）
	ChunkID pgtype.UUID `json:"chunk_id"`
	// Embeddingベクトル（1536次元）
	Vector pgvector_go.Vector `json:"vector"`
	// 使用したEmbeddingモデル名
	Model     string           `json:"model"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

// スナップショット内のファイル・ドキュメント情報
type File struct {
	// ファイルの一意識別子
	ID pgtype.UUID `json:"id"`
	// 所属するスナップショットのID
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	// ソースルートからの相対パス（またはドキュメント識別子）
	Path string `json:"path"`
	// ファイルサイズ（バイト）
	Size int64 `json:"size"`
	// MIMEタイプ形式のコンテンツ種別（例: text/x-go, text/x-python, text/markdown, application/pdf, text/html）
	ContentType string `json:"content_type"`
	// ファイル内容のSHA-256ハッシュ
	ContentHash string `json:"content_hash"`
	// プログラミング言語（go-enryによる自動検出）
	Language pgtype.Text `json:"language"`
	// ドメイン分類（code, architecture, ops, tests, infra）
	Domain    pgtype.Text      `json:"domain"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

// ファイルごとの要約（LLMが生成）
type FileSummary struct {
	// 要約の一意識別子
	ID pgtype.UUID `json:"id"`
	// 対象ファイルのID
	FileID pgtype.UUID `json:"file_id"`
	// LLMが生成した要約（Markdown形式）
	Summary string `json:"summary"`
	// Embeddingベクトル（pgvectorの制約により列全体で次元固定、最初のINSERT時の次元で確定）
	Embedding pgvector_go.Vector `json:"embedding"`
	// メタデータ（モデル名、次元数、生成日時等。metadata.dimに実際の次元数を記録）
	Metadata  []byte           `json:"metadata"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

// Git専用の参照（ブランチ、タグ）管理
type GitRef struct {
	// Git参照の一意識別子
	ID pgtype.UUID `json:"id"`
	// 対象ソースのID（source_type=gitのみ）
	SourceID pgtype.UUID `json:"source_id"`
	// 参照名（ブランチ名またはタグ名: main, develop, v1.0.0 等）
	RefName string `json:"ref_name"`
	// 参照が指すスナップショットのID
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	// 参照の作成日時
	CreatedAt pgtype.Timestamp `json:"created_at"`
	// 参照の更新日時（別のコミットを指すようになった時）
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

// プロダクト（複数のソースをまとめる単位）
type Product struct {
	// プロダクトの一意識別子
	ID pgtype.UUID `json:"id"`
	// プロダクト名（一意）
	Name string `json:"name"`
	// プロダクトの説明
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

// RAG回答の品質フィードバックを記録するテーブル
type QualityNote struct {
	// 品質ノートの一意識別子（UUID）
	ID pgtype.UUID `json:"id"`
	// ビジネス識別子（例: QN-2024-001）
	NoteID string `json:"note_id"`
	// 深刻度（critical: 致命的, high: 高, medium: 中, low: 低）
	Severity string `json:"severity"`
	// 問題の詳細内容
	NoteText string `json:"note_text"`
	// 関連ファイルパスのJSONBリスト
	LinkedFiles []byte `json:"linked_files"`
	// 関連チャンクIDのJSONBリスト
	LinkedChunks []byte `json:"linked_chunks"`
	// レビュー者名
	Reviewer string `json:"reviewer"`
	// ステータス（open: 未解決, resolved: 解決済み）
	Status string `json:"status"`
	// 記録日時
	CreatedAt pgtype.Timestamp `json:"created_at"`
	// 解決日時（解決済みの場合のみ）
	ResolvedAt pgtype.Timestamp `json:"resolved_at"`
}

type SnapshotFile struct {
	ID         pgtype.UUID      `json:"id"`
	SnapshotID pgtype.UUID      `json:"snapshot_id"`
	FilePath   string           `json:"file_path"`
	FileSize   int64            `json:"file_size"`
	Domain     pgtype.Text      `json:"domain"`
	Indexed    bool             `json:"indexed"`
	SkipReason pgtype.Text      `json:"skip_reason"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

// ドキュメント・コードのソース情報（Git、Confluence、PDFなど）
type Source struct {
	// ソースの一意識別子
	ID pgtype.UUID `json:"id"`
	// 所属するプロダクトのID（必須）
	ProductID pgtype.UUID `json:"product_id"`
	// ソース名（一意）
	Name string `json:"name"`
	// ソースタイプ（git/confluence/pdf/redmine/notion/local）
	SourceType string `json:"source_type"`
	// ソースタイプ固有の情報（JSONBフォーマット）。例: Gitの場合 {"url": "git@github.com:...", "default_branch": "main"}、Confluenceの場合 {"base_url": "https://...", "space_key": "..."}
	Metadata  []byte           `json:"metadata"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

// ソースの特定バージョン時点のスナップショット
type SourceSnapshot struct {
	// スナップショットの一意識別子
	ID pgtype.UUID `json:"id"`
	// 対象ソースのID
	SourceID pgtype.UUID `json:"source_id"`
	// バージョン識別子（Gitの場合はcommit_hash、Confluenceの場合はpage_version、PDFの場合はfile_hash等）
	VersionIdentifier string `json:"version_identifier"`
	// インデックス完了フラグ
	Indexed bool `json:"indexed"`
	// インデックス完了日時
	IndexedAt pgtype.Timestamp `json:"indexed_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

// Wiki生成の実行履歴とメタデータ（プロダクト単位のみ）
type WikiMetadatum struct {
	// Wiki生成レコードの一意識別子
	ID pgtype.UUID `json:"id"`
	// 対象プロダクトのID
	ProductID pgtype.UUID `json:"product_id"`
	// Wikiファイルの出力先パス（例: /var/lib/dev-rag/wikis/my-ecommerce/）
	OutputPath string `json:"output_path"`
	// 生成されたWikiファイル数
	FileCount int32 `json:"file_count"`
	// Wiki生成完了日時
	GeneratedAt pgtype.Timestamp `json:"generated_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}
