// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountArchitectureSummaries(ctx context.Context, snapshotID pgtype.UUID) (int64, error)
	CountDirectorySummariesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) (int64, error)
	CountFileSummariesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) (int64, error)
	CreateArchitectureSummary(ctx context.Context, arg CreateArchitectureSummaryParams) (ArchitectureSummary, error)
	CreateDirectorySummary(ctx context.Context, arg CreateDirectorySummaryParams) (DirectorySummary, error)
	CreateFileSummary(ctx context.Context, arg CreateFileSummaryParams) (FileSummary, error)
	CreateWikiMetadata(ctx context.Context, arg CreateWikiMetadataParams) (WikiMetadatum, error)
	DeleteArchitectureSummariesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) error
	DeleteArchitectureSummaryByType(ctx context.Context, arg DeleteArchitectureSummaryByTypeParams) error
	DeleteDirectorySummariesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) error
	DeleteDirectorySummaryByPath(ctx context.Context, arg DeleteDirectorySummaryByPathParams) error
	DeleteFileSummariesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) error
	DeleteFileSummaryByFileID(ctx context.Context, fileID pgtype.UUID) error
	DeleteWikiMetadata(ctx context.Context, id pgtype.UUID) error
	GetAllArchitectureSummaryTypes(ctx context.Context) ([]string, error)
	GetArchitectureSummary(ctx context.Context, arg GetArchitectureSummaryParams) (string, error)
	GetArchitectureSummaryByID(ctx context.Context, id pgtype.UUID) (ArchitectureSummary, error)
	GetDirectorySummaryByID(ctx context.Context, id pgtype.UUID) (DirectorySummary, error)
	GetDirectorySummaryByPath(ctx context.Context, arg GetDirectorySummaryByPathParams) (string, error)
	GetFileSummaryByFileID(ctx context.Context, fileID pgtype.UUID) (FileSummary, error)
	GetFileSummaryByPath(ctx context.Context, arg GetFileSummaryByPathParams) (string, error)
	GetMaxDepthBySnapshot(ctx context.Context, snapshotID pgtype.UUID) (interface{}, error)
	GetWikiMetadata(ctx context.Context, id pgtype.UUID) (WikiMetadatum, error)
	GetWikiMetadataByProduct(ctx context.Context, productID pgtype.UUID) (WikiMetadatum, error)
	HasAllRequiredArchitectureSummaries(ctx context.Context, snapshotID pgtype.UUID) (bool, error)
	ListArchitectureSummariesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) ([]ArchitectureSummary, error)
	ListArchitectureSummariesByType(ctx context.Context, summaryType string) ([]ArchitectureSummary, error)
	ListDirectorySummariesByDepth(ctx context.Context, arg ListDirectorySummariesByDepthParams) ([]DirectorySummary, error)
	ListDirectorySummariesByParentPath(ctx context.Context, arg ListDirectorySummariesByParentPathParams) ([]DirectorySummary, error)
	ListDirectorySummariesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) ([]DirectorySummary, error)
	ListFileSummariesBySnapshot(ctx context.Context, snapshotID pgtype.UUID) ([]FileSummary, error)
	ListWikiMetadata(ctx context.Context) ([]WikiMetadatum, error)
	SearchArchitectureSummariesByEmbedding(ctx context.Context, arg SearchArchitectureSummariesByEmbeddingParams) ([]SearchArchitectureSummariesByEmbeddingRow, error)
	SearchDirectorySummariesByEmbedding(ctx context.Context, arg SearchDirectorySummariesByEmbeddingParams) ([]SearchDirectorySummariesByEmbeddingRow, error)
	SearchFileSummariesByEmbedding(ctx context.Context, arg SearchFileSummariesByEmbeddingParams) ([]SearchFileSummariesByEmbeddingRow, error)
	UpsertArchitectureSummary(ctx context.Context, arg UpsertArchitectureSummaryParams) (ArchitectureSummary, error)
	UpsertDirectorySummary(ctx context.Context, arg UpsertDirectorySummaryParams) (DirectorySummary, error)
	UpsertFileSummary(ctx context.Context, arg UpsertFileSummaryParams) (FileSummary, error)
}

var _ Querier = (*Queries)(nil)
