// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wiki_metadata.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWikiMetadata = `-- name: CreateWikiMetadata :one
INSERT INTO wiki_metadata (product_id, output_path, file_count, generated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (product_id)
DO UPDATE SET
    output_path = EXCLUDED.output_path,
    file_count = EXCLUDED.file_count,
    generated_at = EXCLUDED.generated_at
RETURNING id, product_id, output_path, file_count, generated_at, created_at
`

type CreateWikiMetadataParams struct {
	ProductID   pgtype.UUID      `json:"product_id"`
	OutputPath  string           `json:"output_path"`
	FileCount   int32            `json:"file_count"`
	GeneratedAt pgtype.Timestamp `json:"generated_at"`
}

func (q *Queries) CreateWikiMetadata(ctx context.Context, arg CreateWikiMetadataParams) (WikiMetadatum, error) {
	row := q.db.QueryRow(ctx, createWikiMetadata,
		arg.ProductID,
		arg.OutputPath,
		arg.FileCount,
		arg.GeneratedAt,
	)
	var i WikiMetadatum
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OutputPath,
		&i.FileCount,
		&i.GeneratedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWikiMetadata = `-- name: DeleteWikiMetadata :exec
DELETE FROM wiki_metadata
WHERE id = $1
`

func (q *Queries) DeleteWikiMetadata(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWikiMetadata, id)
	return err
}

const getWikiMetadata = `-- name: GetWikiMetadata :one
SELECT id, product_id, output_path, file_count, generated_at, created_at FROM wiki_metadata
WHERE id = $1
`

func (q *Queries) GetWikiMetadata(ctx context.Context, id pgtype.UUID) (WikiMetadatum, error) {
	row := q.db.QueryRow(ctx, getWikiMetadata, id)
	var i WikiMetadatum
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OutputPath,
		&i.FileCount,
		&i.GeneratedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWikiMetadataByProduct = `-- name: GetWikiMetadataByProduct :one
SELECT id, product_id, output_path, file_count, generated_at, created_at FROM wiki_metadata
WHERE product_id = $1
`

func (q *Queries) GetWikiMetadataByProduct(ctx context.Context, productID pgtype.UUID) (WikiMetadatum, error) {
	row := q.db.QueryRow(ctx, getWikiMetadataByProduct, productID)
	var i WikiMetadatum
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OutputPath,
		&i.FileCount,
		&i.GeneratedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listWikiMetadata = `-- name: ListWikiMetadata :many
SELECT id, product_id, output_path, file_count, generated_at, created_at FROM wiki_metadata
ORDER BY generated_at DESC
`

func (q *Queries) ListWikiMetadata(ctx context.Context) ([]WikiMetadatum, error) {
	rows, err := q.db.Query(ctx, listWikiMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WikiMetadatum{}
	for rows.Next() {
		var i WikiMetadatum
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.OutputPath,
			&i.FileCount,
			&i.GeneratedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
